BASE_TASK_CONFIG_PATH: multion/config/multion_3on_one_scene.yaml
LOG_FILE: non_learning.log
LOG_INTERVAL: 100
VIDEO_OPTION: []  # options: "disk", "tensorboard"
VIDEO_DIR: experiments/non_learning/mon2.0/3on/oracle/train/videos
RESULTS_DIR: experiments/non_learning/mon2.0/3on/oracle/train/00014-nYYcLpSzihC

EVAL:
    SPLIT: train
    # any num greater than the actual episode count evals every episode
    EPISODE_COUNT: 1
    EVAL_NONLEARNING: True
    NONLEARNING:
        # OracleAgent or RandomAgent or HandcraftedAgent
        AGENT: OracleAgent

RL:
  NEW_REWARD_STRUCTURE: True

