ENVIRONMENT:
  MAX_EPISODE_STEPS: 2500
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: MultiObjectNav-v1
  CYL_OBJECTS_PATH: "data/multion_cyl_objects"
  OBJECTS_TYPE: "CYL"
  INCLUDE_DISTRACTORS: True
  
  POSSIBLE_ACTIONS: ["FOUND", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]

  SUCCESS_DISTANCE: 1.5

  SENSORS: ['MULTI_OBJECT_GOAL_SENSOR', 'POINTGOAL_WITH_GPS_COMPASS_SENSOR', 'OBJECT_MAP_SENSOR',
            'ORACLE_MAP_SIZE_SENSOR', 'POSITION_SENSOR', 'ROTATION_SENSOR']

  GOAL_SENSOR_UUID: multiobjectgoal
  
  OBJECT_MAP_SENSOR:
    meters_per_pixel: 0.3
    map_size: 150

  ORACLE_MAP_SIZE_SENSOR:
    meters_per_pixel: 0.3

  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2

  MEASUREMENTS: [
    'EPISODE_LENGTH',
    'DISTANCE_TO_CURR_GOAL', 
    'DISTANCE_TO_MULTI_GOAL', 
    'SUB_SUCCESS', 
    'SUCCESS', 
    'MSPL', 
    'PROGRESS', 
    'PSPL',
    ]

  SUCCESS:
    SUCCESS_DISTANCE: 1.5
  SUB_SUCCESS:
    SUCCESS_DISTANCE: 1.5
  PROGRESS:
    SUCCESS_DISTANCE: 1.5
  DISTANCE_TO_GOAL:
    DISTANCE_TO: POINT
DATASET:
  TYPE: MultiObjectNav-v1
  SPLIT: train
  SCENES_DIR: "data/scene_datasets/"
  NUM_GOALS: 3
  DATA_PATH: "data/3_ON_CYL_{split}/{split}/{split}.json.gz"
  #CONTENT_SCENES: ["00017-oEPjPNSPmzL"]
